### PR TITLE
Home: better screenshots

### LINKED ISSUE #78: Add better screenshots, and more screenshots
Hi guys. the screenshots on the official website, do not do justice to the new mapgen v7! Minetest generates much more beautiful and detailed game maps as they appear in the web site screenshots. I can do some very nice screenshots, so new users can see the dramatic improvements that have been added in Minetest.

With your permission I'll take the task of making me the screenshots, then send the push! Thank you all. I await your permission.

--------------------------

## Overview

(Added by rubenwardy)

condensed info from multiple views:

* Show off Mapgen v7
* photos with mods/subgames
* photos with buildings
* Multiplayer / photos with other players (and with varied armors/skins ?)
* Authentic gameplay footage, not just some random landscape you found after flying around.
* (maybe) texture packs (less important)

### PR DESCRIPTION
**Pull request by Zughy**
Taken by CDB.

Fixes #78 

image

### CODE REVIEW

**Review by rubenwardy — APPROVED** [review]

**Comment by Zughy** [comment]
@LoneWolfHT 5th screen is MTG with just a mod

**Review by LoneWolfHT — APPROVED** [review]
I guess that works

**Comment by kilbith** [comment]
There was also this one I liked a lot: https://pbs.twimg.com/media/FU4oT2daUAAq1jO?format=jpg&name=large

**Review by Niklp09 — APPROVED** [review]

**Comment by Niklp09** [comment]
beautiful

**Comment by sorcerykid** [comment]
> This should probably show at least 1 untextured MTG screenshot so that the initial game isn't a surprise

You're always welcome to make use of any of the screenshots from the JT2 server, since it's basically just a "souped up" version of Minetest Game, but it's still using all classic MTG textures. These are some of the images I'm currently using to promote the server. 

image

**Pull request merged**
