### PR TITLE
Updated the Minetest Game screenshot in /media/gallery, issue #265

### PR DESCRIPTION
**Pull request by blkkatana**
Updated the Minetest Game screenshot in /media/gallery to show dynamic shadows and bloom, as wanted in issue #265. Screenshot was taken in Minetest version 5.9.0-dev.

### CODE REVIEW

**Review by appgurueu — COMMENTED** [review]
Looks good to me, friendlier scenery, showcases rendering a bit better. Have you tried optimizing file size? (Sizes are still acceptably small, but there is a notable increase).

What may be debatable is that the new screenshot doesn't show HUD, but I think it's better (less cluttered) this way.

There is a "downgrade", though: The new screenshot is relatively low res (old one is 1920 x 1080, new one is 1280 x 678).

**Comment by blkkatana** [comment]
I do have the same screenshot with the HUD and a higher resolution (1920 x 1011) if that is preferable.

**Comment by appgurueu** [comment]
Yes, that would be preferable. Why such an odd resolution though? I would expect 1920 x 1024.

**Comment by rollerozxa** [comment]
You should full screen Minetest so it takes a complete 1920x1080 screenshot.

**Comment by grorp** [comment]
The screenshot needs some antialiasing :)

**Comment by blkkatana** [comment]
screenshot
I took a new screenshot. How does it look? It's 1920 x 1080, with SSAA turned up to 4. The odd resolution before was because the screenshot wasn't taken in full screen.

**Comment by sfan5** [comment]
I have this screenshot lying around, which I think showcases the dynamic shadows better. Unfortunately it's not exactly 1080p:
screenshot_20210623_162552

**Comment by blkkatana** [comment]
I like it. Can I use it for my pull request?

**Comment by sfan5** [comment]
Sure.

**Comment by sfan5** [comment]
Alt text in `_data/gallery.yml` also needs updating.

**Comment by blkkatana** [comment]
Why does it need updating?

**Comment by sfan5** [comment]
Nevermind, I accidentally looked at an old revision where it still said "An underwater jungle in Minetest Game".

**Review by sfan5 — APPROVED** [review]

**Pull request merged**
