### PR TITLE
Add link to Doxygen documentation site

### PR DESCRIPTION
**Pull request by ShadowNinja**
(hosted by yours truly, with a number of Doxyfile modifications (PR incoming!))

### CODE REVIEW

**Comment by est31** [comment]
:+1:

**Comment by est31** [comment]
Also good to see that it already supports https.

**Comment by rubenwardy** [comment]
Maybe "Doxygen docs of engine internals" or smth? Developers interested are likely to have heard of doxygen.

**Comment by ShadowNinja** [comment]
I wanted to keep it short so the menu wouldn't be too wide.  That could be done though...

**Comment by est31** [comment]
What about "Engine internals (Doxygen)"?

**Comment by ShadowNinja** [comment]
@est31: Done.

**Comment by est31** [comment]
2cfaf394e33cd51a86419af450cdea27ba7fd9f0

**Pull request closed without merging**
