### PR TITLE
Use well-known CDNs for delivering some scripts

### PR DESCRIPTION
**Pull request by ShadowNinja**
This uses Google's CDN for jQuery and one provided by MaxCDN for Bootstrap.
This allows the files to be served from a geographically closer location,
increases the chances that the file will already be locally cached, and
makes library updates easier.

### CODE REVIEW

**Comment by est31** [comment]
:-1: loading js files from external places means to give them full access to the site. They could add tracker scripts or such.

**Comment by est31** [comment]
Even if they don't add tracker scripts, they already get usage data from the HTTP requests alone, and the referrer.

**Comment by PilzAdam** [comment]
:-1:, see @est31 privacy and security concerns.

**Comment by nerzhul** [comment]
:-1: this is non performant for browser because this don't permit to use proper HTTP/1.1 pipelining for loading all page content

**Comment by ShadowNinja** [comment]
@nerzhul: Pipelining?  Do you mean HTTP/2?  It would have relatively more overhead on HTTP/2, but the main improvement of this is that it's much more likely that the client will already have these cached, which is true no matter the HTTP version.

**Comment by sfan5** [comment]
:-1: because of reasons already talked about

@ShadowNinja: HTTP/1.1 supports pipelining too: https://en.wikipedia.org/wiki/HTTP_pipelining#Implementation_status

**Comment by rubenwardy** [comment]
multiple disapprovals here

**Pull request closed without merging**
