### PR TITLE
Update gallery images

### PR DESCRIPTION
**Pull request by Treer**
A concrete pull request to work with was suggested in #78

These are all FSAA 8 at 1920x1080 with shaders and a good view range etc ([i.e. #78 comment](https://github.com/minetest/minetest.github.io/issues/78#issuecomment-265517608)), made with Minetest version 5 and version 4.17

The gallery shots from this PR needn't be permanent, but consider merging the pull request before discussion of replacements bogs down. If necessary, gallery shots could be updated frequently during discussions, rather than after/never.

### Some rationale and engine coverage for each shot
1. A bright and inviting world, landscape generation, it can look like Minecraft
2. Modability and variety - it doesn't have to look like Minecraft
3. Modability / angled pieces, impressive builds, multiplayer servers, landscape generation
4. Day/night cycle, HUD, wielded items, minimap, underwater scenery
5. Lighting (smooth & dynamic), torches, dungeons, ominous
6. Cave generation, lava and flowing liquids, lighting 

### Preview
minetest gallery

### Reproduction notes
The Original pngs have been uploaded [here](https://github.com/minetest/minetest.github.io/pull/124#issuecomment-424415954). Notes for if future changes/re-renders are needed:
1. mgValleys, seed 1, (-1450,578), Minetest 5.0.0-81c06de
2. [Aotearoa](https://forum.minetest.net/viewtopic.php?t=20770), mgValleys, seed 1, (18548, 1942), Minetest 5.0.0-81c06de
3. Built by [Miniminaut](https://forum.minetest.net/memberlist.php?mode=viewprofile&u=19248) on Hometown (public server using mapgen v7, Minetest 4.17), coordinates (-5640,-10080)
4. mgValleys, seed 1, (-112, -1264), Minetest 5.0.0-81c06de
5. mapgen v7, seed 1, (104,  -392, 277), Minetest 5.0.0-81c06de
6. mapgen v7, seed 1, (4011,  -397, 2095), Minetest 5.0.0-81c06de

### CODE REVIEW

**Comment by rubenwardy** [comment]
I like the selection shown in the preview

I am wondering how to show variety of content, for example different possible games. This could be done later by adding more screenshots, however

**Comment by Ezhh** [comment]
These are definitely better than the current images.

Are there any concerns we need to have around texture licenses (there are some non-MTG ones used there) and whether whoever built those castles is fine with them being used for this?

**Comment by Treer** [comment]
The castle is built by [Miniminaut](https://forum.minetest.net/memberlist.php?mode=viewprofile&u=19248) - I think that whole area is, who is happy to have it as a gallery screenshot :)

The south pacific old growth forest was generated by [Aotearoa](https://forum.minetest.net/viewtopic.php?t=20770), which has textures licensed under CC BY-SA 3.0.

**Comment by Wuzzy2** [comment]
Finally, a selection of screenshots that does not suck. Sadly, it's still heavily biased towards Minetest Game. :-(
But it's better than nothing.

**Comment by paramat** [comment]
It's an improvement so :+1:

**Pull request merged**
