### PR TITLE
Switch from Stylus to SCSS

### PR DESCRIPTION
**Pull request by ShadowNinja**
The motivation for doing this is that Jekyll has SASS/SCSS support built-in, so we don't need Grunt anymore.

(SASS is the name of the program and the old (python/stylus-like) syntax, SCSS is the newer CSS-like syntax)

### CODE REVIEW

**Comment by rubenwardy** [comment]
:+1: but haven't tested

**Comment by Calinou** [comment]
https://github.com/minetest/minetest.github.io/commit/c2402b91d960dd10feb6845fc5f6d3d218f2ace2

**Comment by ShadowNinja** [comment]
@Calinou: Why did you set the commit author to you?

**Comment by Calinou** [comment]
> @Calinou: Why did you set the commit author to you?

I merged the commit by hand, solving the merge conflicts using Atom. That's possibly why the author was "lost".

**Comment by rubenwardy** [comment]
git commit --amend --author "ShadowNinja <email>"

iirc.

**Comment by ShadowNinja** [comment]
@Calinou: both `git merge` and `git rebase` preserve the author.  If "Atom" doesn't, you should submit a bug and not use it 'til it's fixed.

**Pull request closed without merging**
