### PR TITLE
Add background colors to images

### PR DESCRIPTION
**Pull request by Calinou**
This improves perceived performance on slow connections by displaying a background color while the image is loading.

### CODE REVIEW

**Comment by paramat** [comment]
Doesn't seem worth doing, looks worse than a plain colour.
How are the gradient specifications created? Would we have to generate a gradient specification from an image for each image added to a gallery? It doesn't seem automatic.
:-1:

**Comment by Calinou** [comment]
@paramat The gradient specification has to be added manually (since we don't have a build pipeline set up), but the declaration can be generated using [this tool](https://www.npmjs.com/package/resemble-image-cli). Either way, it's not like we add new images to the gallery every month :slightly_smiling_face:

**Comment by rubenwardy** [comment]
I don't think this looks very nice. Perhaps a more subtle appearance, or a solid grey would be better

**Comment by paramat** [comment]
Solid grey is much better as it requires no manual matching to the current images. Also looks better than weird gradients.

**Comment by Calinou** [comment]
I amended the pull request to only add background colors to images on the homepage.

**Review by rubenwardy — DISMISSED** [review]

**Comment by rubenwardy** [comment]
Actually, I think a lighter grey would look better - #ccc for example

**Comment by Calinou** [comment]
@rubenwardy I replaced the background color with `#ccc`.

**Review by rubenwardy — APPROVED** [review]

**Comment by Calinou** [comment]
Bump :slightly_smiling_face: Could this be merged, please? I replaced the gradients with a simple gray color which is easier to maintain if we update the screenshots.

**Pull request merged**
