### PR TITLE
Language translations

### PR DESCRIPTION
**Pull request by zaoqi**
根据浏览器的语言来翻译网页

### CODE REVIEW

**Comment by rubenwardy** [comment]
The site needs to work without Javascript (Although it's fine if it just shows in English without JS, imo, although ideally internationalisation should work without it)

**Comment by zaoqi** [comment]
Now can work without Javascript

**Comment by ShadowNinja** [comment]
The code shouldn't try to download an English translation when that's the default.

This also looks very ad-hoc.  Isn't there a standard way of doing this instead of writing our own system?

**Comment by zaoqi** [comment]
```bash
>locale/en-us.txt
`

**Comment by zaoqi** [comment]
[jQuery.i18n.properties]
<h1>Meet Minetest.</h1> -> <h1 id="meetminetest">Meet Minetest.</h1>
*_en.properties:
meetminetest=Meet Minetest.
*_zh.properties:
meetminetest=遇见Minetest。

**Comment by ShadowNinja** [comment]
I'm aware the file can be created, but it shouldn't be necessary.  If the user's language is english (the majority of our users) they're going at hove to make another request for nothing, which will slow down the page load and waste bandwidth.

The jQuery thing seems much better.  This also looks good: https://github.com/wikimedia/jquery.i18n

**Pull request closed without merging**
