### PR TITLE
Add FontAwesome icons

### PR DESCRIPTION
**Pull request by xdev31**
Hello,
This is pull request to add FontAwesome Icons to website. Team is free to change them how they want.
A preview:
minetesticons2

### CODE REVIEW

**Comment by tobyplowy** [comment]
@xdev31 this wuld Look amazing!

**Comment by xdev31** [comment]
@tobyplow Thanks for Feedback

**Comment by ShadowNinja** [comment]
In #50 CDNs were unwanted, and without one this will make the website substantially heavier.

**Comment by est31** [comment]
@ShadowNinja good point.

**Comment by xdev31** [comment]
@ShadowNinja Thanks for your feedback

**Comment by est31** [comment]
Mhh, just visited the font awesome website, and saw the fonts load very slowly, looking at weird replacement symbols instead. I think we don't need this!

Therefore, :-1:

**Comment by xdev31** [comment]
:( I'm very sorry, if you don't like it. I tried to improve website @est31

**Comment by est31** [comment]
@xdev31 you don't need to be sorry. Its always good if someone tries to improve the website, even if its rejected. Maybe, if other devs agree it will be even merged against my :-1: ...

**Comment by rubenwardy** [comment]
Icons would be nice, but I don't like these particular ones. So :-1: for this PR (but another with nicer icons may get my approval)

**Pull request closed without merging**
