### PR TITLE
Add link to Windows installer

### PR DESCRIPTION
**Pull request by rubenwardy**

### CODE REVIEW

**Comment by rubenwardy** [comment]
Ideally, it should be hosted on Github releases

**Comment by est31** [comment]
Who has created / uplodaded that file to dropbox?

**Comment by rubenwardy** [comment]
I did, using this script: https://gist.github.com/rubenwardy/5397343

I used to make installers for Minetest which featured on the homepage until I moved to Ubuntu. I now have a Windows laptop, and have decided that it's worth the effort.

**Comment by est31** [comment]
I trust you but the builds in the github release are created by core devs only. On the other hand, an official installer for minetest would be really neat. Can we find a core dev who downloads and executes your linked script?

If uploaded to github the installer should be named more like the official ones, something like : `minetest-0.4.13-win64-installer.exe`

Until then I'd :+1: this PR linking to dropbox if the installer is mentioned in the "Unofficial builds" section.

**Comment by rubenwardy** [comment]
> the builds in the github release are created by core devs only

Says who? I've made installers before.

**Comment by nerzhul** [comment]
@rubenwardy dropbox is not the channel to deliver releases. Releases should be done on github only atm.
Also, for windows release, please provide your packaging method to be reproducible by core devs if needed

**Comment by rubenwardy** [comment]
1. Yes, but that doesn't mean someone can add it to the release section
2. I already have.

**Comment by rubenwardy** [comment]
It's fine if a core dev wants to take this up, less work for me. It should become part of the release process.

**Comment by celeron55** [comment]
If needed, I think we can trust rubenwardy on these because he has done them before and they have been published on the website before.

This means a core dev may take rubenwardy's installer and upload it as-is, if rubenwardy indicates it's meant to be an official installer.

**Comment by celeron55** [comment]
I could add rubenwardy to the core team on github if he would like that though. I can't remember if this has been considered before, has it?

**Comment by est31** [comment]
Okay, uploaded it:

https://github.com/minetest/minetest/releases/tag/0.4.13

https://github.com/minetest/minetest/releases/download/0.4.13/minetest-0.4.13-win64-installer.exe

rubenwardy indicated that the installer should be part of the github release in the comment above

**Comment by rubenwardy** [comment]
I don't have the C/++ experience to be a core dev, if that's what you're asking.

It's okay as is, however I'd consider adding more subgames to it.

**Comment by est31** [comment]
:+1:

**Comment by celeron55** [comment]
@rubenwardy Well, you don't have to do or know anything as a core dev, but it would give you access to upload these installers. Everyone trusts you not to mess around with stuff you don't know about so that's not really an issue.

**Comment by Calinou** [comment]
There probably should be a 32-bit Windows installer as well.

Does the installer support Windows XP? This should be mentioned in the release details and on the site.

**Comment by rubenwardy** [comment]
Inno setup claims that they support XP, but I haven't tested it as I don't have XP.
I'll make a 32-bit version soon. It would be nice to have access.

**Comment by celeron55** [comment]
I added the "Trusted non-coredevs" team and added @rubenwardy to it. This should work fairly well.

**Comment by est31** [comment]
hrmmm what about putting the setup files into the util/ subdir of the engine? It will have to evolve, as minetest evolves (new languages added etc), so older versions of it might not apply to newer versions of minetest, and vice versa.

**Pull request merged**
