### PR TITLE
Fixing a broken link to the Fedora RPM

### PR DESCRIPTION
**Pull request by samarth-ramesh**
visiting the link in the website ( from line number 107) is getting an error... using an alternative url for it

### CODE REVIEW

**Comment by wsor4035** [comment]
well, good to see that the link i found worked 👍

**Comment by samarth-ramesh** [comment]
closed, and pending reopen by wsor

**Comment by samarth-ramesh** [comment]
also, thank wsor for the link and the find

**Review by Calinou — APPROVED** [review]
I suppose we can merge this and revert it if `apps.fedoraproject.org` goes back up.

Thanks!

**Pull request merged**
