### PR TITLE
Remove TitilliumWeb fonts

### PR DESCRIPTION
**Pull request by ShadowNinja**
These added 33-84 KB (depending on compression) to the site for (what seems to be) little if any benefit.
This is the second largest single download on the site; it's after the splash image (which could be responsive), and slightly before `jquery.min.js` (which could be served from Google's CDN).

### CODE REVIEW

**Comment by est31** [comment]
Do you have before/after screenshots?

**Comment by ShadowNinja** [comment]
With TitiliumWeb:
2015-12-06-205757_1366x768_scrot

With whatever the default is (probably Oxygen, Arial, or Helvitica):
2015-12-06-205240_1366x768_scrot

**Comment by est31** [comment]
I'm neutral, neither :+1: nor :-1:.

**Comment by Calinou** [comment]
System fonts are inconsistent, which is why they are avoided on the modern Web.

**Comment by ShadowNinja** [comment]
@Calinou: Do they have to be "consistent"?  As long as they work for the user it doesn't seem to really matter.

If this particular font is absolutely necessary we can at least serve it from Google's CDN (https://fonts.googleapis.com/css?family=Titillium+Web).

**Comment by nerzhul** [comment]
@Calinou consistent != looks good

**Comment by ShadowNinja** [comment]
Chrome, with TitilliumWeb:
screenshot_20160307_135225

Without:
screenshot_20160307_135241

**Pull request closed without merging**
