### PR TITLE
Add new mapgens to index.html

### PR DESCRIPTION
**Pull request by Wayward1**
Not quite sure if singlenode should be included, as there's been much discussion over whether or not it belongs in the settings menu at all

### CODE REVIEW

**Comment by est31** [comment]
**cc** @paramat

**Comment by paramat** [comment]
Content is fine. Singlenode should not be included as it's a tool for lua mapgen modders.

**Comment by rubenwardy** [comment]
This contains a mistake: a </p> tag that shouldn't be there

**Comment by Wayward1** [comment]
Oops, sorry about that... Can't believe I missed that

**Comment by sofar** [comment]
Other than that, this is fine, could just merge and --amend before pushing?

**Comment by rubenwardy** [comment]
already been merged

> @est31 merged commit a70de10 into minetest:master 2 days ago

**Comment by est31** [comment]
I'm sorry I've merged without checking for that. Just saw paramat's approval and thought it would be okay.

**Comment by paramat** [comment]
Apologies, i was actually unsure about the use of </p> but made the mistake of not questoning it.
I wrote the 'content' was okay because i'm not qualified in html usage.

**Comment by ExcaliburZero** [comment]
Perhaps a test could be added to the Travis CI builds to check for correct HTML in pull requests?

There are some applications such as [html-proofer](https://github.com/gjtorikian/html-proofer) which can perform such checks.

**Comment by est31** [comment]
@ExcaliburZero that would be a great idea.

**Comment by ExcaliburZero** [comment]
I have made an issue (#69) to discus adding an automated test for valid HTML.

**Pull request merged**
