### PR TITLE
Add press page

### LINKED ISSUE #175: Create an official media kit page for Minetest
Media kit is promotional tool that contains specific information about a website, publication, games, etc. While some people thought media kits are press kits, they are slightly different in nature.

Media kit page will greatly help people who want to share about Minetest on other platforms or websites. It creates a standard guideline on how to promote the game or website.

I propose that the website to have a page of media kit, and at least includes the following:
- [ ] A simple paragraph or catchphrases that can be used to identify Minetest from all other games.
- [ ] The Minetest logo in original colours (at least in SVG, optionally PNG) -downloadable
- [ ] The Minetest logo in white-on-other-colour variant (at least in SVG, optionally PNG) - downloadable
- [ ] The mentions of the official colour codes of Minetest logo (and optionally the blueprint of the logo layout - eg the shapes and the features of the logo: I see cactus, tree, grass, sand, water, cave, is that correct?)
- [ ] A brochure and/or leaflet of Minetest (maybe ask Rubenwardy for this, iirc he has created PDF that he use to print in some conventions before? or create new one if he refuses to include his) - downloadable

Of course, all these should also be licensed the same way as the rest of the website (or mention the specific license if they were not licensed the same way).

I feel that media kit page should be stand-alone page but I don't mind if it's combined with the suggestions in #123

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #175

@tacotexmex I created this as a branch on the actual repo so that PRs can be made against it

image

## todo

- [ ] More descriptions
- [ ] In focus images
- [ ] Typography
- [ ] Social media links
- [ ] Links to developer roadmaps

### CODE REVIEW

**Comment by tacotexmex** [comment]
Nice. Maybe ”Other” can be called ”Pitch”?

I’d also like a tagline, an even shorter description with 5-7 words.

Speaking of text, what should the repo description be called?

> Minetest, an open source infinite-world block sandbox game engine with support for survival and crafting.

**Comment by tacotexmex** [comment]
Regarding typography there probably need to be a discussion arround it since it will change appearance. But let’s start off small-scale: what’s your stance regarding typography?

As for myself I think it’s time that Minetest gets its own distinct typeface. I think this is an interesting problem to solve and so I’d be willing to look into it.

**Comment by tacotexmex** [comment]
I'm starting to think that the Minetest org needs another repo, "meta", for hosting project-specific issues. What do you think?

**Comment by Calinou** [comment]
> As for myself I think it’s time that Minetest gets its own distinct typeface. I think this is an interesting problem to solve and so I’d be willing to look into it.

We're developing a voxel game, not a typeface :slightly_smiling_face:

Creating a typeface with a complete character set is a huge amount of work.

**Comment by tacotexmex** [comment]
I’m very familiar with the amount of work a typeface needs. I’m not necessarily suggesting drawing from scratch. I just want to highlight a need for a distinct typeface.

> We're developing a voxel engine/game

You also develop a website, which involves the Minetest brand, which is why I find this interesting.

It’s not about Titillium per, it’s about strengthening the parts that constitutes a coherent recognizable visual identity of which typography is one. Currently, there’s a bunch of different typefaces in the project (including in the client) which does not help.

I assumed that there’s consensus regarding wanting to strengthen the identity, but if not then carry on. ¯\_(ツ)_/¯

**Comment by Calinou** [comment]
@tacotexmex I think we could eventually review the default fonts used in the client, but this issue should be raised on [minetest/minetest](https://github.com/minetest/minetest).

**Comment by tacotexmex** [comment]
That is good! Does that then mean that this choice of client typeface will dictate the typeface being used on the website?

**Comment by Calinou** [comment]
@tacotexmex Possibly. In any case, I wouldn't use the current client fonts on the website as they look kind of bland.

**Comment by rubenwardy** [comment]
I think typography should be left to another PR

**Comment by tacotexmex** [comment]
Agreed. I’m not even suggesting an ”on-brand” type of font for generic website text, but primarily for headings.

**Comment by tacotexmex** [comment]
> I think typography should be left to another PR

Fair enough, let’s leave it out of this then.

**Pull request closed without merging**
