### PR TITLE
Document browser support for the website

### PR DESCRIPTION
**Pull request by Calinou**
See #220.

### CODE REVIEW

**Comment by rubenwardy** [comment]
N-1 = version before latest?

**Comment by Calinou** [comment]
@rubenwardy Yes; I'm not sure how to make the wording clearer.

**Comment by rubenwardy** [comment]
"Two most recent versions"  or   "Two latest versions"

**Comment by Calinou** [comment]
@rubenwardy I updated the wording.

**Review by rubenwardy — APPROVED** [review]

**Pull request merged**
