### PR TITLE
Remove "About this website" section from community.html

### PR DESCRIPTION
**Pull request by treetrunk**
This removes the "About this website" section from communiy.html as discussed in issue #31 .

### CODE REVIEW

**Comment by rubenwardy** [comment]
:+1:, however the git error needs to be fixed.

**Comment by treetrunk** [comment]
What do you mean? Where are you seeing an error?

**Comment by rubenwardy** [comment]
@treetrunk 	Fix wording and grammar mentioned in issue #23 	6ec4f3f
@treetrunk 	Fix typo in Multiplayer Support section 	f932a72
@treetrunk 	Re-word Subgame section 	0d03c32
@treetrunk 	Fix typo in link to mods in the subgame section 	dbf82f8
@treetrunk 	Remove 'About This Website' section 	5a64606
@treetrunk 	Merge remote-tracking branch 'upstream/master'

only Remove 'About This Website' section 	5a64606 should be there.

**Comment by ShadowNinja** [comment]
You shouldn't be making pulls off master, you should be using feature branches.  Also, use `git pull --rebase upstream master`, not `git merge`, to update your fork.

**Comment by treetrunk** [comment]
There. I think got it now after doing some git resets. Sorry about that. I'm still getting the hang of git. Thanks for your help though!

**Pull request merged**
