### PR TITLE
add new background-downloads.jpg

### PR DESCRIPTION
**Pull request by SpaghettiDeveloper**
Sent, I hope I have done everything correctly. Thank you all.

### CODE REVIEW

**Comment by rubenwardy** [comment]
There's text in the top left

**Comment by SpaghettiDeveloper** [comment]
damn! is true :( sorry,

**Comment by sfan5** [comment]
:+1:

**Comment by ShadowNinja** [comment]
I like the image.

For performance reasons I think that the image should be a progressive JPEG, and probably with a relatively low quality setting (1080p is just really big, especially for 3g devices).  There should also be a PNG version somewhere if we ever want to re-encode it.

**Comment by SpaghettiDeveloper** [comment]
New images I create, follow all the specific questions, this screenshot made in jpg because the official website are all jpg images. When I have time, I create screenshots best, to show the improvements of Minetest 0.4.14: D Thanks to all.

**Comment by Calinou** [comment]
> For performance reasons I think that the image should be a progressive JPEG, and probably with a relatively low quality setting (1080p is just really big, especially for 3g devices).

We can provide several sizes, and let the browser decide of the best one using the `picture` element for example. However, I'm against providing a default version that's less than 1080p, because it'll be blurred on 1080p displays otherwise.

Alternatively, we can keep a 1080p version but blur it more or less (which might still look good), which will decrease the file size.

**Comment by ShadowNinja** [comment]
@Calinou: Yeah, I was just saying that the quality should be a bit lower than usual (which effectively makes it somewhat blurrier due to how JPEG works).  Responsive images would be even better if we got them to work well.

**Comment by rubenwardy** [comment]
https://github.com/minetest/minetest.github.io/commit/9ea3cc3fc5d7f070067fe0e25e4ff4ca6bf7ed8d

**Pull request closed without merging**
