### PR TITLE
Add #Minetest-Hub to the list of official channels.

### PR DESCRIPTION
**Pull request by Megaf**
As in description.
Should we resume or rewrite or reformat anything there?

### CODE REVIEW

**Comment by rubenwardy** [comment]
I suggest only having the first sentence as a description, then linking to hub.minetest.net/intro for the rules

**Comment by Megaf** [comment]
Text was extracted from here -> http://hub.minetest.net/info

**Comment by paramat** [comment]
Text seems good.

**Comment by Ezhh** [comment]
Will be nice to see this added. :)

**Pull request merged**
